version: "3.8"

services:
  edt_web:
    container_name: edt_web
    build: .
    working_dir: /app
    environment:
      - FLASK_APP=edt.py
      - LOG_DIR=/logs
      - FILES_DIR=/files
      - SQLALCHEMY_MIGRATIONS_DIR=/migrations
      - MYSQL_CONNECTOR=mysqlconnector
      - MYSQL_HOST=edt_db:3306
      - MYSQL_WAITER=30:5
    env_file:
      - .env
    volumes:
      - .:/app:ro
      - ./logs:/logs:rw
      - ./migrations:/migrations:rw
      - ./files:/files:rw
    ports:
      - 8000:5000
    links:
      - edt_db
    restart: unless-stopped
    depends_on:
      - edt_db
    command: /bin/sh edt.sh $MIGRATE

  edt_db:
    container_name: edt_db
    image: mysql:8.0.22
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - ./mysql_data:/var/lib/mysql:rw
    restart: unless-stopped
